# Generated by Django 4.0.6 on 2023-01-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField(max_length=1000)),
                ('anio', models.DateField()),
                ('imagen', models.ImageField(upload_to='peliculas')),
                ('genero', models.CharField(choices=[('accion', 'Accion'), ('aventura', 'Aventura'), ('animacion', 'Animacion'), ('drama', 'Drama'), ('cienciaficcion', 'Ciencia Ficcion'), ('terror', 'Terror'), ('misterio', 'Misterio')], max_length=14)),
                ('status', models.CharField(choices=[('RA', 'Recientemente anidada'), ('MV', 'Mas vista'), ('TV', 'Mas valorada')], max_length=2)),
            ],
        ),
    ]
